website/__init__.py
from flask import Flask
from flask_mail import Mail

mail = Mail()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = ''
    
    app.config['DEBUG'] = True #false for production
    app.config['TESTING'] = True #false for production
    app.config['MAIL_SERVER'] = '' #an email service that allows less secure access(gmail doesnt support anymore)
    app.config['MAIL_PORT'] = '' #email port for mail server
    app.config['MAIL_USERNAME'] = ' #email address
    app.config['MAIL_PASSWORD'] = '' #email pw
    app.config['MAIL_USE_TLS'] = True #depending on mail server
    app.config['MAIL_USE_SSL'] = False #depending on mail server
    app.config['MAIL_DEFAULT_SENDER'] = '' 
    
    mail.init_app(app)

    from .views import views
    app.register_blueprint(views,url_prefix="/")

    return app

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_mail import Message
from website import sheets,mail
import paypalrestsdk as prs
from datetime import datetime
import urllib.parse as ul

views = Blueprint('views',__name__)

SUCCESS = False
ADMINMODE = False

prs.configure({
  "mode": "sandbox", # sandbox or live
  "client_id": "", #create a paypal sandbox account
  "client_secret": "" }) 

def sendEmail(title,message,recipients,imageLink=""):
    with mail.connect() as conn:
        for user in recipients:
            msg = Message(title,recipients=[user])
            msg.html = render_template('emailTemplate.html', value=imageLink, message=message)
            conn.send(msg)

@views.route("/about")
def home():
    return render_template("about.html")

@views.route("/registrationFee", methods=['POST'])
def registrationFee():
    payment = prs.Payment({
        "intent": "sale",
        "payer": {
            "payment_method": "paypal"},
        "redirect_urls": {
            "return_url": "http://localhost:3000/payment/execute",
            "cancel_url": "http://localhost:3000/"},
        "transactions": [{
            "item_list": {
                "items": [{
                    "name": "Reserve Spot",
                    "sku": "12345",
                    "price": "5.00",
                    "currency": "USD",
                    "quantity": 1}]},
            "amount": {
                "total": "5.00",
                "currency": "USD"},
            "description": "Reserve your spot at the conference"}]})
    if payment.create():
        print('success')
    else:
        print(payment.error)

    return jsonify({'paymentID':payment.id})

@views.route("/execute", methods=['POST'])
def execute():
    global SUCCESS
    SUCCESS = False
    payment = prs.Payment.find(request.form['paymentID'])
    if payment.execute({'payer_id' : request.form['payerID']}):
        print('payment success')
        flash('payment success',category='success')
        SUCCESS = True
    else:
        print(payment.error)
        SUCCESS = False
    return jsonify({'success' : SUCCESS})

@views.route("/checkStatus", methods=['GET', 'POST'])
def checkStatus():
    if request.method == 'POST':
        email = request.form.get('checkEmail')
        if sheets.checkEmail(email):
            flash('You\'re registered for the conference!', category='success')
        else:
            flash('Sorry, we couldn\'t find you in our systems', category='error')
    return render_template("checkStatus.html")

@views.route("/deleteSpot", methods=['GET','POST'])
def deleteSpot():
    if request.method == 'POST':
        deleteEmail = request.form.get('deleteSpot')
        if sheets.checkEmail(deleteEmail):
            sheets.deleteSpot(deleteEmail)
            flash('You\'ve been removed from the list!', category='success')
            sendEmail('Spot Cancellation Confirmation',"Thanks for letting us know you won't be attending",[deleteEmail])
        else:
            flash("Your name already isn't on the list", category='error')
    return render_template("checkStatus.html")

@views.route("/adminLogin", methods=['GET','POST'])
def adminLogin():
    global ADMINMODE
    if request.method == 'POST':
        password = request.form.get('adminLogin')
        if password == 'blah':
            ADMINMODE = True
        else:
            flash('Please try again', category='error')
            ADMINMODE = False
        if "open" in request.form:
            ADMINMODE = False
    if not ADMINMODE:
        return render_template("adminLogin.html")
    return render_template("adminPage.html", spotsLeft=sheets.getSpotsLeft(), registrantsSheet="", canceledUsersSheet="")

@views.route("/broadcastEmail", methods=['GET','POST'])
def broadcastEmail():
    if request.method == 'POST':
        title=request.form.get('emailTitle')
        message=request.form.get('message')
        imageLink=request.form.get('imageLink')
        recipients=sheets.sheet.col_values(5)
        recipients.pop(0)
        print(message)
        sendEmail(title,message,recipients,imageLink)
        flash('Email successfully sent!',category="success")
    return render_template('adminPage.html')

#title,message,file,recipients

@views.route("/checkIn", methods=['GET','POST'])
def confirmSpot():
    checkInEmail = request.args.get('checkInEmail')
    sheets.checkIn(checkInEmail)
    print('checkIn success')
    return render_template("success.html")


@views.route("/register", methods=['GET','POST'])
def register():
    if request.method == 'POST':
        firstName = request.form.get('firstName')
        lastName = request.form.get('lastName')
        affliation = request.form.get('affliation')
        interest = request.form.get('interest')
        email = request.form.get('email')
        phoneNumber = request.form.get('phoneNumber')
        accomodations = request.form.get('accomodations')
        address = request.form.get('address')
        zip = request.form.get('zip')

        if SUCCESS == False:
            flash('Please make sure you\'ve paid the registration fee', category='error')
        else:
            flash('Successful! We\'ve received your info. Please check your email for details')
            sheets.addToSheets(firstName,lastName,affliation,interest,email,phoneNumber, accomodations, address, zip, datetime.now().strftime("%d/%m/%Y %H:%M"))
            encodedUrl = ul.quote('http://127.0.0.1:8000/checkIn?checkInEmail='+email) #change to actual website
            sendEmail('Conference Registration Details', 'Thank you for your registering for the conference, you\'ve been added into our systems.',[email],"https://api.qrserver.com/v1/create-qr-code/?size=150x150&data="+encodedUrl)
    return render_template("register.html", value=sheets.getSpotsLeft()>0)

website/templates/about.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>About the Conference</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

</head>
<body>
  <ul>
    <li><a href = "/about">About</a></li>
    <li><a href = "/register">Register</a></li>
    <li><a href = "/checkStatus">Check/Edit Status</a></li>
    <li><a href = "/adminLogin">Admin Login</a></li>
  </ul>
<h1 style="text-align:center"> About the Conference - October 8th</h1>
<br/>
<p style="text-align:center">something something. </p>
</body>
</html>

website/templates/adminLogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
  />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
    {% with messages = get_flashed_messages(with_categories=true)%}
{% if messages %}
  {% for category, message in messages %}
  {% if category == 'error' %}
  <div class="alert alert-danger alter-dismissable fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alter-dismissable fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  {% endfor %}
{% endif %}
{% endwith %}
    <ul>
        <li><a href = "/about">About</a></li>
        <li><a href = "/register">Register</a></li>
        <li><a href = "/checkStatus">Check/Edit Status</a></li>
        <li><a href = "/adminLogin">Admin Login</a></li>
    </ul>
    <br/>
    <form method="POST">
        <div class="form-group">
            <label for="adminLogin">Enter admin password</label>
            <input
                type="password"
                class="form-control"
                id="adminLogin"
                name="adminLogin"
                style="width:500px"
            />
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
</body>
</html>

website/templates/adminPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Page</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
    {% with messages = get_flashed_messages(with_categories=true)%}
{% if messages %}
  {% for category, message in messages %}
  {% if category == 'error' %}
  <div class="alert alert-danger alter-dismissable fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alter-dismissable fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  {% endfor %}
{% endif %}
{% endwith %}

    <form method="POST" action="{{url_for('views.adminLogin')}}">
        <input type="submit" name="open" value="Logout">
    </form>
    <br/>
    <form action="{{url_for('views.broadcastEmail')}}" method="POST">
        <h>Email a message to all registrants</h>
        <br/><br/>
        <div class="form-group">
            <label for="emailTitle">Title of email</label>
            <input
                type="text"
                required
                class="form-control"
                id="emailTitle"
                name="emailTitle"
                style="width:400px"
            />
        </div>
        <div class="form-group">
            <label for="message">Message</label>
            <textarea id="message" name="message" class="form-control" style="width:400px;height:200px;"></textarea>
        </div>
        <div class="form-group">
            <label for="imageLink">Image link</label>
            <input
                type="text"
                class="form-control"
                id="imageLink"
                name="imageLink"
                placeholder="optional"
                style="width:400px"
            />
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Send</button>
        </div>
    </form>
    <br/>
    <p>spots left: {{spotsLeft}}</p>
    <h>access the data directly:</h>
    <p><a href={{registrantsSheet}} target="_blank">Registered Users</a></p>
    <p><a href={{canceledUsersSheet}} target="_blank">Canceled Users</a></p>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
</body>
</html>

website/templates/checkStatus.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Check Status</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
  />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
    {% with messages = get_flashed_messages(with_categories=true)%}
{% if messages %}
  {% for category, message in messages %}
  {% if category == 'error' %}
  <div class="alert alert-danger alter-dismissable fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alter-dismissable fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  {% endfor %}
{% endif %}
{% endwith %}
    <ul>
        <li><a href = "/about">About</a></li>
        <li><a href = "/register">Register</a></li>
        <li><a href = "/checkStatus">Check/Edit Status</a></li>
        <li><a href = "/adminLogin">Admin Login</a></li>
    </ul>
    <br/>  
    <form action="{{url_for('views.checkStatus')}}" method="POST">
        <div class="form-group">
            <label for="checkEmail">Enter email to check registration status</label>
            <input
                type="email"
                class="form-control"
                id="checkEmail"
                name="checkEmail"
                style="width:500px"
            />
        </div>
        <button type="submit" class="btn btn-primary">Check</button>
    </form>
    <br/>
    <form action="{{url_for('views.deleteSpot')}}" method="POST">
            <div class="form-group">
                <label for="deleteSpot">Enter email to cancel spot</label>
                <input
                    type="email"
                    class="form-control"
                    id="deleteSpot"
                    name="deleteSpot"
                    style="width:500px"
                />
            </div>
            <button type="submit" class="btn btn-primary">Delete</button>
    </form>
    <br/>
    <p>Please email ___ for any inquiries/issues</p>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
</body>
</html>

website/templates/emailTemplate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h>{{message}}</h>
    <img src= {{value}}>
</body>
</html>

website/templates/register.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Conference Register</title>
  <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
  />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

</head>
<body>

{% with messages = get_flashed_messages(with_categories=true)%}
{% if messages %}
  {% for category, message in messages %}
  {% if category == 'error' %}
  <div class="alert alert-danger alter-dismissable fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alter-dismissable fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  {% endfor %}
{% endif %}
{% endwith %}

<ul>
  <li><a href = "/about">About</a></li>
  <li><a href = "/register">Register</a></li>
  <li><a href = "/checkStatus">Check/Edit Status</a></li>
  <li><a href = "/adminLogin">Admin Login</a></li>
</ul>

<div class="wrapper">
    <form method="POST">
        <h3 align="center">Conference Registration Form</h3>
        <div class="form-group">
            <label for="firstName">First Name</label>
            <input
                type="text"
                required
                class="form-control"
                id="firstName"
                name="firstName"
            />
        </div>
        <div class="form-group">
            <label for="lastName">Last Name</label>
            <input
                type="text"
                required
                class="form-control"
                id="lastName"
                name="lastName"
            />
        </div>
        <div class="form-group">
            <label for="lastName">Affliation</label>
            <input
                type="text"
                required
                class="form-control"
                id="affliation"
                name="affliation"
                placeholder="e.g. school, organiztion, company, etc."
            />
        </div>
        <div class="form-group">
          <label for="interest">Conference Interest</label>
          <select type="text" class="form-control" id="interest" name="interest" required>
            <option value="">Select</option>
            <option value="keynote speech">Keynote Speech</option>
            <option value="career panel">Career Panel</option>
            <option value="technical project presentations">Technical Project Presentations</option>
            <option value="k12 project showcase">K-12 project show-case</option>
          </select>
      </div>
        <div class="form-group">
            <label for="email">Email Address</label>
            <input
                type="email"
                required
                class="form-control"
                id="email"
                name="email"
            />
        </div>
        <div class="form-group">
          <label for="phoneNumber">Phone Number</label>
          <input
              type="tel"
              required
              class="form-control"
              id="phoneNumber"
              name="phoneNumber"
          />
      </div>
      <div class="form-group">
        <label for="accomodations">Accomodations</label>
        <input
            type="text"
            class="form-control"
            id="accomodations"
            name="accomodations"
            placeholder="e.g. eyesight,auditory issues, etc. May be left blank"
        />
    </div>
    <div class="form-group">
      <label for="address">Address</label>
      <input
          type="text"
          required
          class="form-control"
          id="address"
          name="address"
      />
    </div>
    <div class="form-group">
      <label for="zip">Postal Code</label>
      <input
        type="number"
        required
        class="form-control"
        id="zip"
        name="zip"
      />
    </div>
    
<script src="https://www.paypalobjects.com/api/checkout.js"></script>

<div>
  <label>Reserve Spot</label>
  <sub>$5 registration fee*,spots left:</sub> <sub id="availText">{{value}}</sub>
</div>

<div id="paypal-button" class="form-group"></div>

<script>
  paypal.Button.render({
    commit: true,
    style: {
    size: 'responsive',
    tagline: 'false',
    label: 'paypal',
    },
    env: 'sandbox', // Or 'production'
    // Set up the payment:
    // 1. Add a payment callback
    payment: function(data, actions) {
      // 2. Make a request to your server
      return actions.request.post('/registrationFee') 
        .then(function(res) {
          // 3. Return res.id from the response
          return res.paymentID;
        });
    },
    // Execute the payment:
    // 1. Add an onAuthorize callback
    onAuthorize: function(data, actions) {
      // 2. Make a request to your server
      return actions.request.post('/execute', {
        paymentID: data.paymentID,
        payerID:   data.payerID
      })
        .then(function(res) {
          console.log(res.success)
        });
    }
  }, '#paypal-button');
</script>

    <br/>
    <div class="row justify-content-center">
      <button id="submitBtn" type="submit" class="btn btn-primary">Register</button>
    </div>
    <script>
          if('{{value}}'== 'False'){
            document.getElementById("submitBtn").disabled = true
            document.getElementById("paypal-button").style.display='none'
            document.getElementById("availText").style.color='red'
          }else{
            document.getElementById("availText").style.color='green'
          }
    </script>
  </form>
</div>
<p>*Payment status saved for the session. Within the session, if you didn't enter a field but already went through the payment process, reenter your information and the payment can be skipped. Email ____ for any issues/inquiries</p>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
</body>
</html>

website/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success</title>
</head>
<body>
    <img src="https://i.pinimg.com/736x/90/d9/f9/90d9f988a73191ede8a8d4400fb1c91d--anime-neko-manga-anime.jpg">
</body>
</html>